spring:
  application:
    name: backend
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: SJKIM
    password: SJLOVEHE
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update #update? ??? ?? ? ???? ?? ??. validate: ??? != ??? ? ???? / ? ? none, create,create-drop ? ??.
    show-sql: true
    properties:
      hibernate:
        format_sql:true