spring:
  application:
    name: backend
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: SJKIM
    password: SJLOVEHE
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update #update는 엔티티 속성 변경 시 DB TABLE에 자동반영. validate: 엔티티 != TABLE 인 경우 예외 발생 / 그 외 none, create,create-drop 가 있다.
    show-sql: true
    properties:
      hibernate:
        format_sql:true